version: '2.4'
networks:
  jail:
    internal: true
services:
  jail:
    build: .
    read_only: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - setpcap
    security_opt:
      - apparmor=unconfined
      - seccomp=seccomp.json
    networks:
      - jail
