// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: ping.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GraderServiceClient is the client API for GraderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraderServiceClient interface {
	Grade(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type graderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraderServiceClient(cc grpc.ClientConnInterface) GraderServiceClient {
	return &graderServiceClient{cc}
}

func (c *graderServiceClient) Grade(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ping.GraderService/Grade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderServiceServer is the server API for GraderService service.
// All implementations must embed UnimplementedGraderServiceServer
// for forward compatibility
type GraderServiceServer interface {
	Grade(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGraderServiceServer()
}

// UnimplementedGraderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGraderServiceServer struct {
}

func (UnimplementedGraderServiceServer) Grade(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grade not implemented")
}
func (UnimplementedGraderServiceServer) mustEmbedUnimplementedGraderServiceServer() {}

// UnsafeGraderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraderServiceServer will
// result in compilation errors.
type UnsafeGraderServiceServer interface {
	mustEmbedUnimplementedGraderServiceServer()
}

func RegisterGraderServiceServer(s grpc.ServiceRegistrar, srv GraderServiceServer) {
	s.RegisterService(&GraderService_ServiceDesc, srv)
}

func _GraderService_Grade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).Grade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.GraderService/Grade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).Grade(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GraderService_ServiceDesc is the grpc.ServiceDesc for GraderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ping.GraderService",
	HandlerType: (*GraderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Grade",
			Handler:    _GraderService_Grade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping.proto",
}
