name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: redpwn/jail,redpwn/jail:sha-${{ github.sha }}
          cache-from: type=registry,ref=redpwn/jail
          cache-to: type=inline
  jailpow-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - uses: actions/checkout@v2
      - run: go build -v -ldflags '-w -s -extldflags -static' -o jailpow-linux-amd64 ./cmd/jailpow
      - uses: actions/upload-artifact@v2
        with:
          name: jailpow-linux
          path: jailpow-linux-*
  jailpow-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - uses: actions/checkout@v2
      - run: |
          lib_tmp=$(mktemp -d)
          cp /usr/local/opt/gmp/lib/libgmp.a "$lib_tmp"
          go build -v -ldflags "-w -s -extldflags -L$lib_tmp" -o jailpow-darwin-amd64 ./cmd/jailpow
      - uses: actions/upload-artifact@v2
        with:
          name: jailpow-darwin
          path: jailpow-darwin-*
  jailpow-windows:
    runs-on: windows-2019
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-go mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp
      - uses: actions/checkout@v2
      - shell: msys2 {0}
        run: go build -v -ldflags '-w -s -extldflags -static' -o jailpow-windows-amd64.exe ./cmd/jailpow
      - uses: actions/upload-artifact@v2
        with:
          name: jailpow-windows
          path: jailpow-windows-*
  release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - jailpow-linux
      - jailpow-darwin
      - jailpow-windows
    steps:
      - uses: actions/download-artifact@v2
      - uses: softprops/action-gh-release@v1
        with:
          files: jailpow-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
