name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: redpwn/jail,redpwn/jail:sha-${{ github.sha }}
          cache-from: type=registry,ref=redpwn/jail
          cache-to: type=inline
  jailpow-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - uses: actions/checkout@v2
      - run: go build -v -ldflags '-w -s -extldflags -static' -o jailpow-linux-amd64 -o jailpow-linux-amd64 ./cmd/jailpow
      - uses: actions/upload-artifact@v2
        with:
          name: jailpow-linux
          path: jailpow-linux-*
  jailpow-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - uses: actions/checkout@v2
      - run: |
          cp /usr/local/opt/gmp/lib/libgmp.a .
          go build -v -ldflags '-w -s -extldflags -L.' -o jailpow-darwin-amd64 ./cmd/jailpow
      - uses: actions/upload-artifact@v2
        with:
          name: jailpow-darwin
          path: jailpow-darwin-*
  release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - jailpow-linux
      - jailpow-darwin
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jailpow-linux
      - uses: actions/download-artifact@v2
        with:
          name: jailpow-darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: jailpow-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
