name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: |
          find . -type f -name '*.sh' -exec shellcheck '{}' +
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - shellcheck
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: redpwn/jail
          tag_with_ref: true
          tag_with_sha: true
          cache_froms: redpwn/jail:latest
          push: true
