name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: redpwn/jail
          tags: |
            type=sha,format=long
            type=ref,event=tag
      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
