name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: redpwn/jail,redpwn/jail:sha-${{ github.sha }}
          cache-from: type=registry,ref=redpwn/jail
          cache-to: type=inline
