name: CI
on:
  push:
    tags:
      - v*
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: |
          sudo apt-get install -y libgmp-dev
          go build -v -ldflags '-w -s -extldflags -static' -o jailpow-linux-amd64 ./cmd/jailpow
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: jailpow-linux-amd64
